### ISSUE TITLE
Progress Tracker: DisjointSet class methods

### ISSUE THREAD

**Issue by klaudiosinani** [klaussinani/dsforest#3]
## Description

The following issue will act as a progress tracking thread, regarding the implementation of the exposed `DisjointSet` class methods:

### DisjointSet Methods

- [x] `DisjointSet#forestElements`
- [x] `DisjointSet#forestSets`
- [x] `DisjointSet#areConnected(x, y)`
- [x] `DisjointSet#findSet(value) `
- [x] `DisjointSet#getId(value) `
- [x] `DisjointSet#includes(value)`
- [x] `DisjointSet#isEmpty()`
- [x] `DisjointSet#isRepresentative(value)`
- [x] `DisjointSet#isSingleton(value)`
- [x] `DisjointSet#makeSet(value)`
- [x] `DisjointSet#setSize(value)`
- [x] `DisjointSet#union(x, y)`
